openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:2222/api
paths:
  /shop/get-all-products:
    get:
      description: "get all products without pagination"
      parameters: []
      responses:
        "200": { description: OK }
  /shop/show-product/{productId}:
    get:
      summary: "get single product by id"
      parameters:
        - in: path
          name: productId
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
  /shop/add-product:
    post:
      description: "create product"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: integer
              required:
                - title
                - description
                - price
      responses:
        "200":
          description: OK
  /shop/edit-product/{productId}:
    post:
      description: ""
      parameters:
        - in: path
          name: productId
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: integer
              required:
                - title
                - description
                - price
      responses:
        "200":
          description: OK
  /shop/remove-product/{id}:
    delete:
      description: ""
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
